apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: cgroup-enhancer
  name: cgroup-enhancer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cgroup-enhancer-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cgroup-enhancer
  namespace: cgroup-enhancer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cgroup-enhancer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cgroup-enhancer-role
subjects:
- kind: ServiceAccount
  name: cgroup-enhancer
  namespace: cgroup-enhancer
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cgroup-enhancer-manager
  namespace: cgroup-enhancer
  labels:
    control-plane: cgroup-enhancer-manager
spec:
  selector:
    matchLabels:
      control-plane: cgroup-enhancer-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: cgroup-enhancer-manager
    spec:
      containers:
      - command:
        - /manager
        image: cgroup-enhancer:latest
        imagePullPolicy: Always
        name: manager
        env:
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 0
          privileged: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
          - mountPath: /run/containerd/containerd.sock
            name: containersock
          - mountPath: /sys/fs/cgroup
            name: cgroup
      serviceAccountName: cgroup-enhancer
      terminationGracePeriodSeconds: 10
      hostPID: true
      volumes:
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: containersock
          hostPath:
            path: /run/containerd/containerd.sock
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 50
